### ISSUE TITLE
reserve() doesn't look like it should return a correct model

### ISSUE THREAD

**Issue by matthewgrossman** [parq-app/parq-api#20]
https://github.com/parq-app/parq-api/blob/master/models/reservation.js#L116

This line returns a reservation that has never been overwritten. Why would this be up to date with all the changes thus far?

**Comment by matthewgrossman** [comment]
Make sure that the time and all data being returned is actually correct on reserve

**Comment by kenzshelley** [comment]
Have checked that it is
